// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

import { BaseNumbers } from "./baseNumbers";
export namespace DutchNumeric {
	export const LangMarker = 'Nl';
	export const RoundNumberIntegerRegex = `(honderd|duizend|miljoen|miljard|biljoen)`;
	export const ZeroToNineIntegerRegex = `(drie|zeven|acht|vier|vijf|nul|negen|een|één|twee|zes)`;
	export const NegativeNumberTermsRegex = `((min|negatief)\\s+)`;
	export const NegativeNumberSignRegex = `^${NegativeNumberTermsRegex}.*`;
	export const AnIntRegex = `(een|één)(?=\\s)`;
	export const TenToNineteenIntegerRegex = `(zeventien|dertien|veertien|achttien|negentien|vijftien|zestien|elf|twaalf|tien)`;
	export const TensNumberIntegerRegex = `(zeventig|twintig|dertig|tachtig|negentig|veertig|vijftig|zestig)`;
	export const SeparaIntRegex = `(((${TenToNineteenIntegerRegex}|(${ZeroToNineIntegerRegex}(en|ën)${TensNumberIntegerRegex})|${TensNumberIntegerRegex}|${ZeroToNineIntegerRegex})(\\s*${RoundNumberIntegerRegex})*))|${RoundNumberIntegerRegex}|((${AnIntRegex}?(\\s*${RoundNumberIntegerRegex})+))`;
	export const AllIntRegex = `((((${TenToNineteenIntegerRegex}|(${ZeroToNineIntegerRegex}(en|ën)${TensNumberIntegerRegex})|${TensNumberIntegerRegex}|(${ZeroToNineIntegerRegex}|${AnIntRegex}))?(\\s*${RoundNumberIntegerRegex}))\\s*(en\\s*)?)*${SeparaIntRegex})`;
	export const PlaceHolderPureNumber = `\\b`;
	export const PlaceHolderDefault = `\\D|\\b`;
	export const NumbersWithPlaceHolder = (placeholder: string) => { return `(((?<!\\d+\\s*)-\\s*)|(?<=\\b))\\d+(?!(\\,\\d+[a-zA-Z]))(?=${placeholder})`; }
	export const NumbersWithSuffix = `(((?<!\\d+\\s*)-\\s*)|(?<=\\b))\\d+\\s*(K|k|M|T|G)(?=\\b)`;
	export const RoundNumberIntegerRegexWithLocks = `(?<=\\b)\\d+\\s*${RoundNumberIntegerRegex}(?=\\b)`;
	export const NumbersWithDozenSuffix = `(((?<!\\d+\\s*)-\\s*)|(?<=\\b))\\d+\\s+dozijn(en)?(?=\\b)`;
	export const AllIntRegexWithLocks = `((?<=\\b)${AllIntRegex}(?=\\b))`;
	export const AllIntRegexWithDozenSuffixLocks = `(?<=\\b)(((een\\s+)?half\\s+dozijn)|(${AllIntRegex}\\s+dozijn(en)?))(?=\\b)`;
	export const RoundNumberOrdinalRegex = `(honderdste|duizendste|miljoenste|miljardste|biljoenste)`;
	export const BasicOrdinalRegex = `(eerste|tweede|derde|vierde|vijfd(e|en)|zesde|zevende|achtst(e|en)|negende|tiend(e|en)|elfde|twaalfde|dertiende|veertiende|vijftiende|zestiende|zeventiende|achttiende|negentiende|twintigste|dertigste|veertigste|vijftigste|zestigste|zeventigste|tachtigste|negentigste)`;
	export const SuffixBasicOrdinalRegex = `(((((${ZeroToNineIntegerRegex}(en|ën)${TensNumberIntegerRegex})|${TensNumberIntegerRegex}|${ZeroToNineIntegerRegex}|${AnIntRegex})(\\s+${RoundNumberIntegerRegex})+)\\s+(en\\s+)?)*(${TensNumberIntegerRegex}(\\s+|\\s*-\\s*|\\s*/\\s*))?${BasicOrdinalRegex})`;
	export const SuffixRoundNumberOrdinalRegex = `((${AllIntRegex}\\s+)${RoundNumberOrdinalRegex})`;
	export const AllOrdinalRegex = `(${SuffixBasicOrdinalRegex}|${SuffixRoundNumberOrdinalRegex})`;
	export const OrdinalSuffixRegex = `(?<=\\b)((\\d*(1e|2e|3e|4e|5e|6e|7e|8e|9e|0e))|(1ste|2de|3de|4de|5de|6de|7de|8ste|9de|0de)|([0-9]*1[0-9]de)|([0-9]*[2-9][0-9]ste)|([0-9]*[0](1ste|2de|3de|4de|5de|6de|7de|8ste|9de|0de)))(?=\\b)`;
	export const OrdinalNumericRegex = `(?<=\\b)(\\d{1,3}(\\s*.\\s*\\d{3})*\\s*e)(?=\\b)`;
	export const OrdinalRoundNumberRegex = `(?<!(één|een)\\s+)${RoundNumberOrdinalRegex}`;
	export const OrdinalDutchRegex = `(?<=\\b)${AllOrdinalRegex}(?=\\b)`;
	export const FractionNotationWithSpacesRegex = `(((?<=\\W|^)-\\s*)|(?<=\\b))\\d+\\s+\\d+[/]\\d+(?=(\\b[^/]|$))`;
	export const FractionNotationRegex = `(((?<=\\W|^)-\\s*)|(?<=\\b))\\d+[/]\\d+(?=(\\b[^/]|$))`;
	export const FractionNounRegex = `(?<=\\b)(${AllIntRegex}\\s+(en\\s+)?)?(${AllIntRegex})(\\s+|\\s*-\\s*|\\s*/\\s*)(((${AllOrdinalRegex})|(${RoundNumberOrdinalRegex}))n?|halven|vierdes)(?=\\b)`;
	export const FractionNounWithArticleRegex = `(?<=\\b)(${AllIntRegex}\\s+(en\\s)?)?(een)(\\s+|\\s*-\\s*|\\s*/\\s*)((${AllOrdinalRegex})|(${RoundNumberOrdinalRegex})|half|halve|kwart)(?=\\b)`;
	export const FractionPrepositionRegex = `(?<=\\b)(?<numerator>(${AllIntRegex})|((?<!,)\\d+))\\s+(op|op\\s+de|van\\s+de|uit|uit\\s+de)\\s+(?<denominator>(${AllIntRegex})|(\\d+)(?!,))(?=\\b)`;
	export const FractionPrepositionWithinPercentModeRegex = `(?<=\\b)(?<numerator>(${AllIntRegex})|((?<!,)\\d+))\\s+over\\s+(?<denominator>(${AllIntRegex})|(\\d+)(?!,))(?=\\b)`;
	export const AllPointRegex = `((\\s+${ZeroToNineIntegerRegex})+|(\\s+${SeparaIntRegex}))`;
	export const AllFloatRegex = `${AllIntRegex}(\\s+komma)${AllPointRegex}`;
	export const DoubleWithMultiplierRegex = `(((?<!\\d+\\s*)-\\s*)|((?<=\\b)(?<!\\d+,)))\\d+,\\d+\\s*(K|k|M|G|T|B|b)(?=\\b)`;
	export const DoubleExponentialNotationRegex = `(((?<!\\d+\\s*)-\\s*)|((?<=\\b)(?<!\\d+,)))(\\d+(,\\d+)?)e([+-]*[1-9]\\d*)(?=\\b)`;
	export const DoubleCaretExponentialNotationRegex = `(((?<!\\d+\\s*)-\\s*)|((?<=\\b)(?<!\\d+,)))(\\d+(,\\d+)?)\\^([+-]*[1-9]\\d*)(?=\\b)`;
	export const DoubleDecimalPointRegex = (placeholder: string) => { return `(((?<!\\d+\\s*)-\\s*)|((?<=\\b)(?<!\\d+,)))\\d+,\\d+(?!(,\\d+))(?=${placeholder})`; }
	export const DoubleWithoutIntegralRegex = (placeholder: string) => { return `(?<=\\s|^)(?<!(\\d+)),\\d+(?!(,\\d+))(?=${placeholder})`; }
	export const DoubleWithRoundNumber = `(((?<!\\d+\\s*)-\\s*)|((?<=\\b)(?<!\\d+,)))\\d+,\\d+\\s+${RoundNumberIntegerRegex}(?=\\b)`;
	export const DoubleAllFloatRegex = `((?<=\\b)${AllFloatRegex}(?=\\b))`;
	export const CurrencyRegex = `(((?<=\\W|^)-\\s*)|(?<=\\b))\\d+\\s*(B|b|m|t|g)(?=\\b)`;
	export const NumberWithSuffixPercentage = `(${BaseNumbers.NumberReplaceToken})(\\s*)(%|procent|percentage)`;
	export const FractionNumberWithSuffixPercentage = `((${BaseNumbers.FractionNumberReplaceToken})\\s+of)`;
	export const NumberWithPrefixPercentage = `(percentage van|procent van|procenten van)(\\s*)(${BaseNumbers.NumberReplaceToken})`;
	export const NumberWithPrepositionPercentage = `(${BaseNumbers.NumberReplaceToken})\\s*(in|out\\s+of)\\s*(${BaseNumbers.NumberReplaceToken})`;
	export const TillRegex = `(tot|--|-|—|——|~)`;
	export const MoreRegex = `((groter|hoger|meer)(\\s+dan|\\s+als)?|boven|over|>)`;
	export const LessRegex = `((minder|lager|kleiner)(\\s+dan|\\s+als)?|beneden|onder|<)`;
	export const EqualRegex = `(gelijk(\\s+(aan|als))?|=)`;
	export const MoreOrEqual = `((${MoreRegex}\\s+of\\s+${EqualRegex})|minstens|niet\\s+${LessRegex}|>\\s*=)`;
	export const MoreOrEqualSuffix = `(en|of)\\s+(meer|groter|hoger|grotere)(?!\\s+dan|?!\\s+als)`;
	export const LessOrEqual = `((${LessRegex}\\s+of\\s+${EqualRegex})|maximum|niet\\s+${MoreRegex}|<\\s*=)`;
	export const LessOrEqualSuffix = `(en|of)\\s+(minder|lager|kleiner)(?!\\s+dan|?!\\s+als)`;
	export const NumberSplitMark = `(?![,.](?!\\d+))`;
	export const MoreRegexNoNumberSucceed = `((groter|hoger|meer)((?!\\s+dan|?!\\s+als)|\\s+(dan(?!(\\s*\\d+))))|(boven|over)(?!(\\s*\\d+)))`;
	export const LessRegexNoNumberSucceed = `((minder|lager|kleiner)((?!\\s+dan|?!\\s+als)|\\s+(dan(?!(\\s*\\d+))))|(beneden|onder)(?!(\\s*\\d+)))`;
	export const EqualRegexNoNumberSucceed = `(gelijk?((?!\\s+(aan|tot))|(\\s+(aan|tot)(?!(\\s*\\d+)))))`;
	export const OneNumberRangeMoreRegex1 = `(${MoreOrEqual}|${MoreRegex})\\s*(de\\s+)?(?<number1>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)`;
	export const OneNumberRangeMoreRegex2 = `(?<number1>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)\\s*${MoreOrEqualSuffix}`;
	export const OneNumberRangeMoreSeparateRegex = `(${EqualRegex}\\s+(?<number1>(${NumberSplitMark}.)+)(\\s+of\\s+)${MoreRegexNoNumberSucceed})|(${MoreRegex}\\s+(?<number1>(${NumberSplitMark}.)+)(\\s+of\\s+)${EqualRegexNoNumberSucceed})`;
	export const OneNumberRangeLessRegex1 = `(${LessOrEqual}|${LessRegex})\\s*(de\\s+)?(?<number2>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)`;
	export const OneNumberRangeLessRegex2 = `(?<number2>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)\\s*${LessOrEqualSuffix}`;
	export const OneNumberRangeLessSeparateRegex = `(${EqualRegex}\\s+(?<number1>(${NumberSplitMark}.)+)(\\s+of\\s+)${LessRegexNoNumberSucceed})|(${LessRegex}\\s+(?<number1>(${NumberSplitMark}.)+)(\\s+of\\s+)${EqualRegexNoNumberSucceed})`;
	export const OneNumberRangeEqualRegex = `${EqualRegex}\\s*(the\\s+)?(?<number1>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)`;
	export const TwoNumberRangeRegex1 = `tussen\\s*(de\\s+)?(?<number1>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)\\s*en\\s*(de\\s+)?(?<number2>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)`;
	export const TwoNumberRangeRegex2 = `(${OneNumberRangeMoreRegex1}|${OneNumberRangeMoreRegex2})\\s*(en|maar|,)\\s*(${OneNumberRangeLessRegex1}|${OneNumberRangeLessRegex2})`;
	export const TwoNumberRangeRegex3 = `(${OneNumberRangeLessRegex1}|${OneNumberRangeLessRegex2})\\s*(en|maar|,)\\s*(${OneNumberRangeMoreRegex1}|${OneNumberRangeMoreRegex2})`;
	export const TwoNumberRangeRegex4 = `(van\\s+)?(?<number1>((?!((\\.(?!\\d+))|(,(?!\\d+))|\\van\\b)).)+)\\s*${TillRegex}\\s*(de\\s+)?(?<number2>((?!((\\.(?!\\d+))|(,(?!\\d+)))).)+)`;
	export const AmbiguousFractionConnectorsRegex = `^[.]`;
	export const DecimalSeparatorChar = ',';
	export const FractionMarkerToken = 'van de';
	export const NonDecimalSeparatorChar = '.';
	export const HalfADozenText = 'zes';
	export const WordSeparatorToken = 'en';
	export const WrittenDecimalSeparatorTexts = [ 'komma' ];
	export const WrittenGroupSeparatorTexts = [ 'punt' ];
	export const WrittenIntegerSeparatorTexts = [ 'en' ];
	export const WrittenFractionSeparatorTexts = [ 'uit','van de','op de','en' ];
	export const HalfADozenRegex = `(een\\s+)?half\\s+dozijn`;
	export const GrossRegex = `(een\\s+)?gros`;
	export const DigitalNumberRegex = `((?<=\\b)(honderd|duizend|miljoen|miljard|biljoen|dozijn?)(?=\\b))|((?<=(\\d|\\b))(k|t|m|g|b)(?=\\b))`;
	export const CardinalNumberMap: ReadonlyMap<string, number> = new Map<string, number>([["nul", 0],["een", 1],["één", 1],["twee", 2],["drie", 3],["vier", 4],["vijf", 5],["zes", 6],["zeven", 7],["acht", 8],["negen", 9],["tien", 10],["elf", 11],["twaalf", 12],["dozijn", 12],["dertien", 13],["veertien", 14],["vijftien", 15],["zestien", 16],["zeventien", 17],["achttien", 18],["negentien", 19],["twintig", 20],["dertig", 30],["veertig", 40],["vijftig", 50],["zestig", 60],["zeventig", 70],["tachtig", 80],["negentig", 90],["honderd", 100],["gros", 144],["duizend", 1000],["miljoen", 1000000],["miljard", 1000000000],["biljoen", 1000000000000]]);
	export const OrdinalNumberMap: ReadonlyMap<string, number> = new Map<string, number>([["nulde", 0],["eerste", 1],["tweede", 2],["secundair", 2],["half", 2],["halve", 2],["derde", 3],["vierde", 4],["kwart", 4],["vijfde", 5],["vijfden", 5],["zesde", 6],["zevende", 7],["achtste", 8],["achtsten", 8],["negende", 9],["tiende", 10],["tienden", 10],["elfde", 11],["twaalfde", 12],["dertiende", 13],["veertiende", 14],["vijftiende", 15],["zestiende", 16],["zeventiende", 17],["achttiende", 18],["negentiende", 19],["twintigste", 20],["dertigste", 30],["veertigste", 40],["vijftigste", 50],["zestigste", 60],["zeventigste", 70],["tachtigste", 80],["negentigste", 90],["honderdste", 100],["duizendste", 1000],["miljoenste", 1000000],["miljardste", 1000000000],["biljoenste", 1000000000000],["biljardste", 1000000000000000],["triljoenste", 1000000000000000000]]);
	export const RoundNumberMap: ReadonlyMap<string, number> = new Map<string, number>([["honderd", 100],["duizend", 1000],["miljoen", 1000000],["miljard", 1000000000],["biljoen", 1000000000000],["biljard", 1000000000000000],["triljard", 1000000000000000000],["honderdste", 100],["duizendste", 1000],["miljoenste", 1000000],["miljardste", 1000000000],["biljoenste", 1000000000000],["biljardste", 1000000000000000],["triljoenste", 1000000000000000000],["honderdsten", 100],["duizendsten", 1000],["miljoensten", 1000000],["miljardsten", 1000000000],["biljoensten", 1000000000000],["dozijn", 12],["gros", 144],["k", 1000],["m", 1000000],["g", 1000000000],["b", 1000000000],["t", 1000000000000]]);
}
